# Generated by Django 4.1.1 on 2022-10-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_remove_workoutset_exercise_remove_workoutset_workout_and_more'),
        ('exercise_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOut',
            new_name='WorkoutSet',
        ),
    ]
