# Generated by Django 4.1.1 on 2022-10-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_remove_workoutset_exercise_remove_workoutset_workout_and_more'),
        ('exercise_tracker', '0002_rename_workout_workoutset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['set']},
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='exercise_tracker.session'),
        ),
    ]
