# Generated by Django 4.1.1 on 2022-10-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0004_session_workout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='focus_area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
