# Generated by Django 4.1.1 on 2022-10-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0005_session_focus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='focus_area',
            field=models.JSONField(default=list, null=True),
        ),
    ]
