# Generated by Django 4.1.1 on 2022-10-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_remove_workoutset_exercise_remove_workoutset_workout_and_more'),
        ('exercise_tracker', '0007_alter_session_focus_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={},
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='session',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='set',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField(default=0)),
                ('rep', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='exercise.exercise')),
            ],
            options={
                'ordering': ('set',),
            },
        ),
    ]
