# Generated by Django 4.1.1 on 2022-10-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_remove_workoutset_exercise_remove_workoutset_workout_and_more'),
        ('exercise_tracker', '0009_workoutset_exercise_set_workoutset_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='exercise_set',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='exercise_tracker.workoutset'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='exercise.exercise'),
        ),
    ]
