# Generated by Django 4.1.1 on 2022-10-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0010_remove_workoutset_exercise_set_exerciseset_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutset', to='exercise_tracker.workoutset'),
        ),
    ]
