# Generated by Django 4.1.1 on 2022-10-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0012_alter_exerciseset_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='exercise',
        ),
    ]
