# Generated by Django 4.1.1 on 2022-10-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0014_exerciseset_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_set', to='exercise_tracker.workoutset'),
        ),
    ]
