# Generated by Django 4.1.1 on 2022-10-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0015_alter_exerciseset_workout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutSet',
            new_name='Workout',
        ),
    ]
