# Generated by Django 4.1.1 on 2022-10-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0018_alter_exerciseset_rep_alter_exerciseset_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='workout_day',
            field=models.TextField(max_length=100),
        ),
    ]
