# Generated by Django 4.1.1 on 2022-10-20 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_tracker', '0020_remove_exerciseset_exercise_workout_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
    ]
