# Generated by Django 4.1.1 on 2022-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_tracker', '0023_alter_exerciseset_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
