# Generated by Django 4.1.1 on 2022-09-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_bodyparts_alter_exercise_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='gitUrl',
            new_name='gifUrl',
        ),
    ]
