# Generated by Django 4.1.1 on 2022-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_rename_giturl_exercise_gifurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='bodyParts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target',
            field=models.JSONField(default=list),
        ),
    ]
