# Generated by Django 4.1.1 on 2022-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise_equipment_alter_exercise_bodyparts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gifUrl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
