# Generated by Django 4.1.1 on 2022-10-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_exercise_gifurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bodyParts', models.JSONField(default=list)),
                ('gifUrl', models.CharField(default='', max_length=255)),
                ('target', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('rep',)},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='bodyParts',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='gifUrl',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target',
        ),
        migrations.AddField(
            model_name='exercise',
            name='rep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='exercise.exercise')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='exercise.movement'),
        ),
    ]
