# Generated by Django 4.1.1 on 2022-10-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_movement_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('movement',)},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('exercise',)},
        ),
    ]
