# Generated by Django 4.1.1 on 2022-10-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_alter_exercise_options_alter_set_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField(default=1)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='set',
            name='number',
        ),
        migrations.AddField(
            model_name='exercise',
            name='bodyParts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='gifUrl',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='set',
            name='set',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Movements', to='exercise.workout'),
        ),
    ]
