# Generated by Django 4.1.1 on 2022-10-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_workoutset_delete_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='created_at',
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='focus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='rep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='set',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
