# Generated by Django 4.1.1 on 2022-10-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_remove_workout_exercise_remove_workout_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='exercise.workout'),
        ),
    ]
