# Generated by Django 4.1.1 on 2022-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
